import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {spawnSync} from "node:child_process";
import {fileURLToPath} from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
test("local installer uses fixed offline bytes and rejects changed dependencies before installation", {timeout:60000}, t=>{
 const temporary=fs.mkdtempSync(path.join(os.tmpdir(),"kdna local installer-"));
 t.after(()=>fs.rmSync(temporary,{recursive:true,force:true}));
 const copy=path.join(temporary,"checkout");
 fs.cpSync(root,copy,{recursive:true,filter:p=>!p.split(path.sep).some(n=>[".git","node_modules"].includes(n))});
 const env={...process.env,npm_config_cache:path.join(temporary,"empty-cache")};
 const run=()=>spawnSync("bash",[path.join(copy,"install-cli.sh")],{cwd:temporary,env,encoding:"utf8",timeout:30000});
 const installed=run();assert.equal(installed.status,0,installed.stdout+installed.stderr);
 assert.match(installed.stdout,/No global binary was installed/);
 assert.doesNotMatch(installed.stdout,/plan-load|kdna load|kdna attach|kdna-studio create/);
 const cli=path.join(copy,"mcp-server/node_modules/@aikdna/kdna-cli/src/cli.js");
 assert.ok(fs.statSync(cli).isFile());
 const first=fs.readFileSync(cli);
 const repeated=run();assert.equal(repeated.status,0,repeated.stdout+repeated.stderr);
 assert.deepEqual(fs.readFileSync(cli),first);
 const args=spawnSync("bash",[path.join(copy,"install-cli.sh"),"--global"],{cwd:temporary,env,encoding:"utf8"});
 assert.equal(args.status,2);assert.match(args.stderr,/no registry or global/);
 assert.deepEqual(fs.readFileSync(cli),first);
 const file=path.join(copy,"mcp-server/package.json"),pkg=JSON.parse(fs.readFileSync(file));
 pkg.dependencies["@aikdna/kdna-cli"]="latest";fs.writeFileSync(file,JSON.stringify(pkg));
 fs.rmSync(path.join(copy,"mcp-server/node_modules"),{recursive:true,force:true});
 const rejected=run();assert.equal(rejected.status,1);
 assert.equal(fs.existsSync(path.join(copy,"mcp-server/node_modules")),false);
 pkg.dependencies["@aikdna/kdna-cli"]="file:vendor/aikdna-kdna-cli-0.38.0-rc.component-semantics.1.tgz";
 fs.writeFileSync(file,JSON.stringify(pkg));
 fs.unlinkSync(path.join(copy,"mcp-server/vendor/fast-uri-3.1.7.tgz"));
 const missing=run();assert.equal(missing.status,1);assert.match(missing.stderr,/ENOENT/);
 assert.equal(fs.existsSync(path.join(copy,"mcp-server/node_modules")),false);
});
